#!/usr/bin/env python
# -*- coding: utf-8 -*-

from kam.app.controllers.model_controller import create
from kam.app.controllers.database_controller import (
    create_database,
    drop_database,
    migrate,
    seed)

import click


@click.group()
def kam():
    pass


@click.group()
def generate():
    pass


@generate.command("model")
@click.argument(
    "model_name")
@click.argument(
    "instance_variables",
    nargs=-1)
def generate_model(model_name, instance_variables):

    create(model_name, instance_variables)


@generate.command("migration")
@click.argument(
    "name")
@click.argument(
    "columns",
    nargs=-1)
def generate_migration():

    pass


@click.command("db:drop")
def db_drop():

    drop_database()


@click.command("db:create")
def db_create():

    create_database()


@click.command("db:migrate")
def db_migrate():

    migrate()


@click.command("db:rollback")
def db_rollback():

    pass


@click.command("db:seed")
def db_seed():

    seed()


@click.command("db:reset")
def db_reset():

    pass


if __name__ == '__main__':
    kam.add_command(generate)
    kam.add_command(db_drop)
    kam.add_command(db_create)
    kam.add_command(db_migrate)
    kam.add_command(db_seed)
    kam.add_command(db_rollback)
    kam.add_command(db_reset)
    kam()
